# Generated by Django 3.2.5 on 2021-07-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('addresse_physique', models.CharField(max_length=255)),
                ('Type_pe', models.CharField(max_length=255)),
                ('raison_social', models.CharField(max_length=255)),
                ('addresse_commande', models.CharField(max_length=255)),
                ('addresse_facture', models.CharField(max_length=255)),
                ('statut_juridique', models.CharField(max_length=255)),
                ('annee_creation', models.IntegerField()),
                ('registre_commerce', models.CharField(max_length=255)),
                ('capital_social', models.IntegerField()),
                ('chiffre_affaire', models.IntegerField()),
                ('note_fournisseur', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
