# Generated by Django 3.2.5 on 2021-07-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(default=' email@email.com', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='Type_pe',
            field=models.CharField(blank=True, default='Non Définit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='addresse_commande',
            field=models.CharField(blank=True, default='Non Définit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='addresse_facture',
            field=models.CharField(blank=True, default='Non Définit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='annee_creation',
            field=models.IntegerField(blank=True, default='Non Définit', null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='capital_social',
            field=models.IntegerField(blank=True, default='Non Définit', null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='chiffre_affaire',
            field=models.IntegerField(blank=True, default='Non Définit', null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='identifier',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='note_fournisseur',
            field=models.IntegerField(blank=True, default='Non Définit', null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='raison_social',
            field=models.CharField(blank=True, default='Non Définit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='registre_commerce',
            field=models.CharField(blank=True, default='Non Définit', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='statut_juridique',
            field=models.CharField(choices=[('GIE', 'GIE'), ('SURL', 'SURL'), ('SAU', 'SAU'), ('SARL', 'SARL'), ('SARLU', 'SARLU'), ('SAS', 'SAS'), ('SCP', 'SCP'), ('SA', 'SA'), ('SNC', 'SNC'), ('SUCCURSALE', 'SUCCURSALE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='telephone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
