# Generated by Django 3.2.5 on 2021-07-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210707_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='annee_creation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='capital_social',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='chiffre_affaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='note_fournisseur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
